### ISSUE TITLE
OpnSense Support?

### ISSUE THREAD

**Issue by CeeBeeEh** [tinwhisker/tplink-eapcontroller-pfsense#2]
Hi, I'm not too familiar with the codebases of either pfSense or OpnSense, but I was curious if this could be adapted as a plugin for OpnSense.

Thanks

**Comment by tinwhisker** [comment]
You'll probably find this or other forks should work as-is for OpnSense or FreeBSD, as this script is more 'FreeBSD' focused than pf/Opn specific.

Really, the only reason 'pfSense' is even mentioned is because:
- I was planning to add GUI elements.
- It was the target system.
